### ISSUE TITLE
hi there! project still active?

### ISSUE THREAD

**Issue by dni** [jimmysitu/bitcoind-openwrt-packages#2]
Hi got some questions: 
are you still using the bitcoind on your router? 
is this project still working?
thinking about running a lighting node on my openwrt router, any possibility of a update to the latest bitcoind?

**Comment by jimmysitu** [comment]
Hi, dni
This project is not active any more, since bitcoind full node require 200GB disk and >1GHz CPU, and most router do not meet this minimum requirement.
I am not sure the minimum HW requirement for a lighting node, but I think it is not hard to upgrade to latest bitcoind to support it.
Good luck
